from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# Dummy data of students' marks
students_marks = [
    {"name": "BW", "marks": 71},
    {"name": "GN", "marks": 3},
    {"name": "2iJQYMr7L", "marks": 39},
    {"name": "DU2v3l", "marks": 80},
    {"name": "A", "marks": 49},
    {"name": "Fbf6Xqbl", "marks": 79},
    {"name": "uIUi5v2", "marks": 54},
    {"name": "o8", "marks": 74},
    {"name": "I98GFqIm9", "marks": 58},
    {"name": "3oS", "marks": 79},
    {"name": "Iyh", "marks": 81},
    {"name": "i3g", "marks": 60},
    {"name": "1eedVA5F", "marks": 53},
    {"name": "yLlsalPnq", "marks": 85},
    {"name": "aVNx", "marks": 75},
    {"name": "Whs0qG", "marks": 76},
    {"name": "EGL3ku2teO", "marks": 31},
    {"name": "cr8OhZ7XrJ", "marks": 9},
    {"name": "T", "marks": 63},
    {"name": "BCfu", "marks": 58},
    {"name": "XGIFc9Q9Lf", "marks": 37},
    {"name": "Dv8CK3rMh", "marks": 42},
    {"name": "HTL0c5", "marks": 95},
    {"name": "t", "marks": 60},
    {"name": "iNaKO", "marks": 71},
    {"name": "RNU10DIyVL", "marks": 82},
    {"name": "Dwh6", "marks": 53},
    {"name": "bV", "marks": 12},
    {"name": "AU", "marks": 0},
    {"name": "a0EALdq", "marks": 48},
    {"name": "Q", "marks": 80},
    {"name": "luG6", "marks": 18},
    {"name": "wmGe8BEFtD", "marks": 92},
    {"name": "0xMK00fxQZ", "marks": 74},
    {"name": "jnEw", "marks": 41},
    {"name": "rOrmTBYh", "marks": 10},
    {"name": "9hidE", "marks": 90},
    {"name": "Q9UrKMtps", "marks": 43},
    {"name": "hZ5lhgG8mA", "marks": 9},
    {"name": "7nNr7ytgA", "marks": 13},
    {"name": "WEJ8b", "marks": 67},
    {"name": "0roBFbEU", "marks": 24},
    {"name": "Aihd4G7q", "marks": 65},
    {"name": "rQ", "marks": 71},
    {"name": "sgnX", "marks": 92},
    {"name": "WSIQDvc", "marks": 69},
    {"name": "vhYf", "marks": 66},
    {"name": "alOK6y", "marks": 34},
    {"name": "fmSQC", "marks": 20},
    {"name": "OHgLAzN", "marks": 17},
    {"name": "l7K", "marks": 90},
    {"name": "4C", "marks": 39},
    {"name": "Y3Q5ld", "marks": 15},
    {"name": "agesJ3ToH", "marks": 11},
    {"name": "9FoFSWcx", "marks": 58},
    {"name": "UQuCS", "marks": 22},
    {"name": "IEgPbBJL", "marks": 18},
    {"name": "0", "marks": 47},
    {"name": "h7", "marks": 52},
    {"name": "5l9", "marks": 54},
    {"name": "Ko", "marks": 62},
    {"name": "QOC", "marks": 27},
    {"name": "SOwCi", "marks": 52},
    {"name": "o399yEbHG", "marks": 42},
    {"name": "WkLe", "marks": 51},
    {"name": "AdGAQekq", "marks": 9},
    {"name": "EeEIBc", "marks": 46},
    {"name": "rEF", "marks": 99},
    {"name": "GPM", "marks": 20},
    {"name": "6k", "marks": 6},
    {"name": "x", "marks": 59},
    {"name": "RsjjROBTz", "marks": 6},
    {"name": "29UMQPT", "marks": 72},
    {"name": "r2DmMeJoK", "marks": 27},
    {"name": "d4o", "marks": 87},
    {"name": "RGdKk085", "marks": 46},
    {"name": "BClIJYMfd", "marks": 55},
    {"name": "Y2Jb", "marks": 0},
    {"name": "1Y", "marks": 56},
    {"name": "a5gwqscXuv", "marks": 89},
    {"name": "yRIjs", "marks": 14},
    {"name": "D1XC7iMsL", "marks": 97},
    {"name": "BffaJ3", "marks": 9},
    {"name": "5LqZ", "marks": 59},
    {"name": "N2N", "marks": 99},
    {"name": "XmPaiH4W", "marks": 20},
    {"name": "Hq", "marks": 37},
    {"name": "PIZ", "marks": 13},
    {"name": "YuWcb0qaSb", "marks": 49},
    {"name": "L", "marks": 12},
    {"name": "OmHswEtde", "marks": 53},
    {"name": "H", "marks": 31},
    {"name": "E9X9p4p0C", "marks": 43},
    {"name": "vGrpRWwUut", "marks": 30},
    {"name": "70sF", "marks": 71},
    {"name": "tW3cU", "marks": 86},
    {"name": "hJwMGhFri", "marks": 20},
    {"name": "Pj", "marks": 44},
    {"name": "VcxSSyH4R", "marks": 11},
    {"name": "g", "marks": 14},
]

students_marks = {student["name"]: student["marks"] for student in students}


@app.route('/api', methods=['GET'])
def get_marks():
    names = request.args.getlist('name')
    marks = [students_marks.get(name, "Not Found") for name in names]
    return jsonify({"marks": marks})


if __name__ == '__main__':
    app.run(debug=True)
